services:
  postgresql:
    image:
      postgres:16
    env_file:
      - .env
    restart: always
    volumes:
      - ./data/shoppingmall-db:/var/lib/postgresql/data


    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  prometheus:
    image: prom/prometheus:v2.7.2
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus.yml
    ports:
      - "9090:9090"


  pushgateway:
    image: prom/pushgateway:v0.6.0
    restart: always
    ports:
      - '9091:9091'

  grafana:
    image: grafana/grafana:6.0.2
    ports:
      - '3000:3000'
