bootJar {
    enabled = false
}

jar {
    enabled = true
}
dependencies {


    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

    // 로그까지 쓰려면
    implementation 'org.slf4j:slf4j-api'
    runtimeOnly 'ch.qos.logback:logback-classic'

    implementation 'org.apache.commons:commons-csv:1.11.0'
    implementation 'org.springframework.boot:spring-boot-starter-batch'


    testImplementation 'org.springframework.batch:spring-batch-test'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'


    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'


}

test {
    useJUnitPlatform()
}